import { Router } from "express";
import { protect } from "../middleware/auth";
import { getCart, addToCart, updateCartItem, removeFromCart, clearCart } from "../controllers/cart.controller";
const router = Router();
router.use(protect);
router.get("/", getCart);
router.post("/", addToCart);
router.put("/:beanId", updateCartItem);
router.delete("/:beanId", removeFromCart);
router.delete("/", clearCart);
export default router;